/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.NguoiDung;
import Service.NDService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThuyVT
 */
public class QLND extends javax.swing.JFrame {
    List<NguoiDung> listND = new ArrayList<>();
    NDService service = new NDService();
    DefaultTableModel defaultTable = new DefaultTableModel();
    
    /**
     * Creates new form QLND
     */
    public QLND() {
        initComponents();
        
        // Khoi tao gia tri cho defaultTable
        defaultTable = (DefaultTableModel) tblListNguoiDung.getModel();
        
        // Hien thi du lieu khi khoi day chuong trinh
        fillToTable();
        
        // Hien thi phan tu vi tri thu 2
        fillToForm(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngRole = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        rdoUser = new javax.swing.JRadioButton();
        rdoAdmin = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListNguoiDung = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkTrangThai = new javax.swing.JCheckBox();
        btnXuat = new javax.swing.JButton();
        btnNhap = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        cboViTriCV = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("QUAN LY NGUOI DUNG");

        jLabel2.setText("Nhap userName");

        jLabel3.setText("Nhap email");

        jLabel4.setText("Nhap password");

        btngRole.add(rdoUser);
        rdoUser.setSelected(true);
        rdoUser.setText("User");

        btngRole.add(rdoAdmin);
        rdoAdmin.setText("Admin");

        jLabel5.setText("Quyen truy câp");

        tblListNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "UserName", "Email", "Password", "Vi tri CV", "Quyen truy cap", "Trang thai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListNguoiDungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListNguoiDung);

        jLabel6.setText("Trang thai");

        jLabel7.setText("Vi tri cong viec");

        chkTrangThai.setText("Kich hoat");

        btnXuat.setText("Xuat");
        btnXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXuatMouseClicked(evt);
            }
        });

        btnNhap.setText("Nhap");
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");

        btnXoa.setText("Xoa");

        btnSapXep.setText("Sap xep");

        btnTim.setText("Tim");

        cboViTriCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinh vien", "Giang vien", "Nhan vien" }));
        cboViTriCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboViTriCVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(rdoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtUserName))
                                            .addGap(20, 20, 20)))
                                    .addComponent(chkTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboViTriCV, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTim)
                                    .addComponent(btnXuat)
                                    .addComponent(btnXoa)
                                    .addComponent(btnSua)
                                    .addComponent(btnNhap)
                                    .addComponent(btnSapXep))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXuat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhap))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoUser)
                            .addComponent(rdoAdmin)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(chkTrangThai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboViTriCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSapXep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTim)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatMouseClicked
        // TODO add your handling code here:
        fillToTable();
    }//GEN-LAST:event_btnXuatMouseClicked

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        if (!validateND()) {
            return;
        }
        // TODO add your handling code here:
        NguoiDung nd = new NguoiDung();
        // Lay gia tri tu txtUserName.getText gan cho thuoc tinh userName 
        // cua nguoidung
        nd.setUserName(txtUserName.getText().trim());
        // Lay gia tri tu txtEmail.getText gan cho thuoc tinh email
        // cua nguoidung        
        nd.setEmail(txtEmail.getText().trim());
        // Lay gia tri txtPassword.getText gan cho thuoc tinh password
        // cua nguoidung
        nd.setPassWord(txtPassword.getText().trim());
        
        // C1:
        if (rdoUser.isSelected()) {
            nd.setQuyen(1);
        }  else {
            nd.setQuyen(2);
        }
        // C2:
        nd.setQuyen(rdoAdmin.isSelected() ? 2 : 1);
        // Checkbox trang thai 
        nd.setStatus(chkTrangThai.isSelected());
        // Lay gia tri tu comboBox
        nd.setViTri(cboViTriCV.getSelectedItem().toString());
        
        // KHAI BAO DOI TUONG NGUOI DUNG
//        NguoiDung nd1 = new NguoiDung(txtUserName.getText(),
//                txtEmail.getText(), txtPassword.getText(), 
//                cboViTriCV.getSelectedItem().toString(), 
//                rdoUser.isSelected() ? 1 : 2, chkTrangThai.isSelected());
        // Goi service them doi tuong nguoi dung moi
        service.add(nd);
        // Do du lieu len tren bang
        fillToTable();
    }//GEN-LAST:event_btnNhapActionPerformed

    private void tblListNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListNguoiDungMouseClicked
        // TODO add your handling code here:
        // Lay ra vi tri dong duoc click chon
        int rowIndex = tblListNguoiDung.getSelectedRow();
        
        // Do du lieu len bang
        if (rowIndex >= 0 && rowIndex < listND.size()) {
                fillToForm(rowIndex);
        }
    }//GEN-LAST:event_tblListNguoiDungMouseClicked

    private void cboViTriCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboViTriCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboViTriCVActionPerformed
    // 
    private void fillToForm(int rowIndex) {
        // Lay ra doi tuong nguoi dung tai rowIndex
        NguoiDung nd = listND.get(rowIndex);
        // Do thuoc tinh userName len txtUserName
        txtUserName.setText(nd.getUserName());
        // Do thuoc tinh email len txtEmail
        txtEmail.setText(nd.getEmail());
        // Do thuoc tinh password len txtPassword
        txtPassword.setText(nd.getPassWord());
        // Chon User khi quyen = 1
        if (nd.getQuyen() == 1) {
            rdoUser.setSelected(true);
        } else {
            rdoAdmin.setSelected(true);
        }
        // Do thuoc tinh trang thai len chkTrangThai
        chkTrangThai.setSelected(nd.isStatus());
        // Do thuoc tinh vi tri len cboViTriCV
        cboViTriCV.setSelectedItem(nd.getViTri());
    }
    // DO DU LIEU VAO BANG
    private void fillToTable() {
        // Do du lieu tu dong dau tien
        defaultTable.setRowCount(0);
        // Lay danh sach nguoi dung tu service
        listND = service.getListNguoiDung();
        
        for (NguoiDung nd : listND) {
            defaultTable.addRow(new Object[] { nd.getUserName(), nd.getEmail(), nd.getPassWord(), 
                                                                nd.getViTri(), nd.getQuyen() == 1 ? "User" : "Admin", nd.isStatus()
            });
        }
    }
    
    private boolean validateND() {
        if (txtUserName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username khong duoc de trong");
            return false;
        } else if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email khong duoc de trong");
            return false;
        } else if (txtPassword.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password khong duoc de trong");
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLND.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLND().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuat;
    private javax.swing.ButtonGroup btngRole;
    private javax.swing.JComboBox<String> cboViTriCV;
    private javax.swing.JCheckBox chkTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoUser;
    private javax.swing.JTable tblListNguoiDung;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
